services:
  - type: web
    name: nana-deep-platform
    env: python
    region: frankfurt
    plan: free
    buildCommand: -m pip install --upgrade pip setuptools wheel
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
